name: find_sport
description: FindSport

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  get_storage: ^2.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  mask_text_input_formatter: ^2.8.0
  yandex_mapkit: ^3.3.3
  json_annotation: ^4.8.1
  dio: ^5.4.0
  retrofit: ^4.0.3
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/
    - assets/language/